[package]
name = "noise"
version = "0.1.0"
authors = ["Volker Mische <volker.mische@gmail.com>"]
repository = "https://github.com/pipedown/noise.git"
homepage = "https://github.com/pipedown/noise.git"
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "Nested Object Inverted Search Engine"
build = "build.rs"


[dependencies]
capnp = "0.7.4"
rustc-serialize= "0.3.19"
stemmer = "0.3.2"
unicode-normalization = "0.1.2"

[dependencies.rocksdb]
git = "https://github.com/vmx/rust-rocksdb.git"
branch = "vmx"

[dependencies.unicode-segmentation]
git = "https://github.com/vmx/unicode-segmentation.git"
branch = "unicode-word-indices"


[build-dependencies]
capnpc = "0.7.2"
