[package]
name = "noise_search"
version = "0.2.1"
authors = ["Damien Katz <me@damienkatz.com>", "Volker Mische <volker.mische@gmail.com>"]
repository = "https://github.com/pipedown/noise.git"
homepage = "https://github.com/pipedown/noise.git"
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "Nested Object Inverted Search Engine"
build = "build.rs"

[lib]
name = "noise_search"
crate-type = ["lib"]


[dependencies]
rustc-serialize = "0.3.19"
stemmer = "0.3.2"
unicode-normalization = "0.1.2"
unicode-segmentation = "0.1.2"
rocksdb = "0.6.0"
varint = "0.9.0"
uuid = { version = "0.3", features = ["v4"] }

